# C++
CONFIG_CPP=y

#Console
CONFIG_CONSOLE=y

#Enable builtin LOG system
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_CBPRINTF_FP_SUPPORT=y

#Sensor
CONFIG_SENSOR=y
CONFIG_MPU6050=y
CONFIG_MPU6050_TRIGGER_NONE=y #Enable polling mode

#PWM for MX1508
CONFIG_PWM=y